---
# Handler to handle common notifications. Handlers are called by other plays.
# See https://docs.ansible.com/ansible/2.5/user_guide/playbooks_reuse_roles.html#role-dependencies
# on how to include handlers from multiple roles.
#
# meta/main.yml:
# dependencies:
#   - { role: mit.nginx-handlers }

- name: Apache configtest
  ansible.builtin.command: apache2ctl configtest
  register: apache_configtest
  listen: Reload apache
  changed_when: false

- name: Reload apache
  ansible.builtin.service:
    name: apache2
    state: reloaded
  when: apache_configtest.rc == 0
  listen: Reload apache

- name: Nginx configtest
  ansible.builtin.command: nginx -t
  register: nginx_configtest
  listen: Reload nginx
  changed_when: false

- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  when: nginx_configtest.rc == 0
  listen: Reload nginx

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
- name: Php7.0-fpm configtest
  ansible.builtin.command: php-fpm7.0 --test
  register: php70_fpm_configtest
  listen: Reload php7.0-fpm
  changed_when: false

- name: Reload php7.0-fpm
  ansible.builtin.service:
    name: php7.0-fpm
    state: reloaded
  when: php70_fpm_configtest.rc == 0
  listen: Reload php7.0-fpm

- name: Php7.3-fpm configtest
  ansible.builtin.command: php-fpm7.3 --test
  register: php73_fpm_configtest
  listen: Reload php7.3-fpm
  changed_when: false

- name: Reload php7.3-fpm
  ansible.builtin.service:
    name: php7.3-fpm
    state: reloaded
  when: php73_fpm_configtest.rc == 0
  listen: Reload php7.3-fpm

- name: Php7.4-fpm configtest
  ansible.builtin.command: php-fpm7.4 --test
  register: php74_fpm_configtest
  listen: Reload php7.4-fpm
  changed_when: false

- name: Reload php7.4-fpm
  ansible.builtin.service:
    name: php7.4-fpm
    state: reloaded
  when: php74_fpm_configtest.rc == 0
  listen: Reload php7.4-fpm

- name: Php8.0-fpm configtest
  ansible.builtin.command: php-fpm8.0 --test
  register: php80_fpm_configtest
  listen: Reload php8.0-fpm
  changed_when: false

- name: Reload php8.0-fpm
  ansible.builtin.service:
    name: php8.0-fpm
    state: reloaded
  when: php80_fpm_configtest.rc == 0
  listen: Reload php8.0-fpm

- name: Php8.1-fpm configtest
  ansible.builtin.command: php-fpm8.1 --test
  register: php81_fpm_configtest
  listen: Reload php8.1-fpm
  changed_when: false

- name: Reload php8.1-fpm
  ansible.builtin.service:
    name: php8.1-fpm
    state: reloaded
  when: php81_fpm_configtest.rc == 0
  listen: Reload php8.1-fpm

- name: Php8.2-fpm configtest
  ansible.builtin.command: php-fpm8.2 --test
  register: php82_fpm_configtest
  listen: Reload php8.2-fpm
  changed_when: false

- name: Reload php8.2-fpm
  ansible.builtin.service:
    name: php8.2-fpm
    state: reloaded
  when: php82_fpm_configtest.rc == 0
  listen: Reload php8.2-fpm
