---
# Handler to handle common notifications. Handlers are called by other plays.
# See https://docs.ansible.com/ansible/2.5/user_guide/playbooks_reuse_roles.html#role-dependencies
# on how to include handlers from multiple roles.
#
# meta/main.yml:
# dependencies:
#   - { role: mit.nginx-handlers }

- name: apache configtest
  command: apache2ctl configtest
  register: apache_configtest
  listen: "Reload apache"

- name: Reload apache
  service: name=apache2 state=reloaded
  when: apache_configtest.rc == 0
  listen: "Reload apache"

- name: nginx configtest
  command: /etc/init.d/nginx configtest
  register: nginx_configtest
  listen: "Reload nginx"

- name: Reload nginx
  service: name=nginx state=reloaded
  when: nginx_configtest.rc == 0
  listen: "Reload nginx"

- name: Restart nginx
  service: name=nginx state=restarted

- name: php7.0-fpm configtest
  command: php-fpm7.0 --test
  register: php70_fpm_configtest
  listen: "Reload php7.0-fpm"

- name: Reload php7.0-fpm
  service: name=php7.0-fpm state=reloaded
  when: php70_fpm_configtest.rc == 0
  listen: "Reload php7.0-fpm"

- name: php7.3-fpm configtest
  command: php-fpm7.3 --test
  register: php73_fpm_configtest
  listen: "Reload php7.3-fpm"

- name: Reload php7.3-fpm
  service: name=php7.3-fpm state=reloaded
  when: php73_fpm_configtest.rc == 0
  listen: "Reload php7.3-fpm"

- name: php7.4-fpm configtest
  command: php-fpm7.4 --test
  register: php74_fpm_configtest
  listen: "Reload php7.4-fpm"

- name: Reload php7.4-fpm
  service: name=php7.4-fpm state=reloaded
  when: php74_fpm_configtest.rc == 0
  listen: "Reload php7.4-fpm"

